# This same file can also be found in repo TradeCalc-image.
# This deploys a custom nginx image that I used Jenkins and Podman VM to build then push to docker.io
# This is a yml manifest for deploying on kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: my-custom-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx-deployment
  namespace: my-custom-nginx
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/jsanderson104/stuff:my-nginx
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: custom-image-svc
  namespace: my-custom-nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
